### ISSUE TITLE
micro-c data

### ISSUE THREAD

**Issue by gorliver** [dozmorovlab/SpectralTAD#14]
Hi,
I have a micro-c data and would like to try SpectralTAD for TAD calling. In the SpectralTAD paper the highest resolution tested is 10kb. Most micro-c data can reach to a resolution of hundreds bp. I wonder have test SpectralTAD on micro-c data? Any suggestions are highly appreciated.

**Comment by mdozmorov** [comment]
Resolution and sparsity (and sequencing depth) are connected. I'm not sure about the level of sparsity in micro-C data. Spectral decomposition can detect signal in sparse data, but everything has its limits. I would definitely use SpectralTAD on micro-C data, checking sparsity and visualizing the results.

**Comment by gorliver** [comment]
Thanks for your prompting response. Definitely go ahead with  SpectralTAD！

**Comment by gorliver** [comment]
Hi @mdozmorov , do you suggest using the raw counts of the matrix or the balanced counts?

**Comment by mdozmorov** [comment]
We recommend raw data. In our experience, balancing leads to loss of some TADs, not many, but it does. That is explainable because equal visibility constraint in balancing would make some TAD borders less pronounced. 

Please, see https://github.com/dozmorovlab/SpectralTAD/issues/13#issuecomment-1883086402 for more parameters we used.
