### ISSUE TITLE
Differences between TAD levels

### ISSUE THREAD

**Issue by sespesogil** [dozmorovlab/SpectralTAD#4]
Hi! Congrats for the tool!

I have a question regarding the multi-level TAD approach, I realized that many times the levels are calling the same TAD region. Is this an expected behavior? Should I use a single level instead when I see this? See an example here:

![image](https://user-images.githubusercontent.com/42008709/148202365-9aacf760-2ad5-4c8c-bc94-f6090edcad07.png)

Thanks a lot! Happy New Year!

S.

**Comment by mdozmorov** [comment]
Yes, it can happen. SpectralTAD calls the first-level TADs, then tries to call 2nd and 3rd. If no subTADs can be detected, coordinates of the first-level TAD are saved. It will typically happen when the matrices are sparse - there's not enough information to call deeper-level TADs. This is typically happening from the 2nd level, as in your example. A few workarounds: 1) Limit TAD level to 2; 2) Increase `window_size`, e.g., `window_size = 200`; 3) Analyse Hi-C data at lower-resolution, e.g., at 50kb instead of 10kb. Those may be suboptimal, but sequencing depth is the main limiting factor when calling hierarchical TADs, and that's why we set `level = 1` as the default. 

We typically call TADs at the first level, but with different window sizes. Here is the example with window sizes 50 and 200. Red/green - different samples. So, green boundaries remain the same irrespectively of window size, but more red boundaries are detected at window size 50. Those are finer-level TADs.
![image](https://user-images.githubusercontent.com/864945/148319630-02836091-45cb-4866-ba2f-72d26fde1495.png)

**Comment by sespesogil** [comment]
Ok! 

Thanks a lot for the detailed explanation! That helps. 

S.

**Comment by mdozmorov** [comment]
Thanks, @sespesogil, for using our tool. I'll plan to update the vignette with those explanations. Please, ask more questions, and I hope SpectralTAD will be useful for you.
